//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isvb.dev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ComentId { get; set; }
        public int PostPostId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Post Post { get; set; }
    }
}
