//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isvb.dev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int VisitorId { get; set; }
        public string VisitorIP { get; set; }
        public string VisitorCountry { get; set; }
        public string Time { get; set; }
        public string UserId { get; set; }
    }
}
